//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane_Otomasyonu_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class zKaynaklar
    {
        public int kaynak_id { get; set; }
        public string kaynak_ad { get; set; }
        public string kaynak_yazar { get; set; }
        public string kaynak_yayinevi { get; set; }
        public string kaynak_sayfasayisi { get; set; }
    }
}
