//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane_Otomasyonu_2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registrations
    {
        public int RegistrationID { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> bookID { get; set; }
        public Nullable<System.DateTime> a_date { get; set; }
        public Nullable<System.DateTime> b_date { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Users Users { get; set; }
    }
}
